pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'devops',
                url: 'https://github.com/samudraladinesh371-max/flask-devops-app'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('devops-project') {
                    sh 'docker build -t flask-devops-app .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker stop flask-container || true'
                sh 'docker rm flask-container || true'
            }
        }

        stage('Run New Container') {
            steps {
                sh 'docker run -d -p 5000:5000 --name flask-container flask-devops-app'
            }
        }
    }
}
